app/routes.py
import logging

from flask import Blueprint, abort, flash, redirect, render_template, request, url_for
from flask.typing import ResponseReturnValue
from flask_paginate import get_page_parameter  # type: ignore
from werkzeug.exceptions import HTTPException, InternalServerError, NotFound

from app import db, services
from app.forms import AccessButtonForm, ContactEmailSearchForm, JobEmailSearchForm, MailDeleteButtonForm, NjkMemoForm
from app.models import ContactEmail, JobEmail

bp = Blueprint("main", __name__)
logger: logging.Logger = logging.getLogger(__name__)

# ページ送り機能の1ページ当たり表示件数
PER_PAGE: int = 10


@bp.route("/")
def index() -> ResponseReturnValue:
    """トップ画面"""
    return render_template("index.html")


@bp.route("/contact-emails", methods=["GET", "DELETE"])
def list_contact_emails() -> ResponseReturnValue:
    """問い合わせメール一覧画面"""
    form = ContactEmailSearchForm(request.args)

    # 検索フォームの不正な入力値をクリア
    is_valid, cleaned_params = services.validate_input(form)

    if not is_valid:
        # 不正な値のクエリパラメータをクリアするためのリダイレクト
        return redirect(url_for("main.list_contact_emails", **cleaned_params))  # type: ignore

    # フォームの検索結果
    query = ContactEmail.query
    query = services.search_contact_emails(query=query, form=form)

    # 並べ替え機能
    order = request.args.get("order", "desc")
    query = services.sort_emails_by_received_at(query=query, model=ContactEmail, order=order)

    # ページ送り機能
    page = request.args.get(get_page_parameter(), type=int, default=1)
    mails, pagination = services.paginate_query(query=query, page=page, per_page=PER_PAGE)

    delete_button_form = MailDeleteButtonForm()
    access_button_form = AccessButtonForm()

    return render_template(
        "list_contact_emails.html",
        mails=mails,
        form=form,
        pagination=pagination,
        delete_button_form=delete_button_form,
        access_button_form=access_button_form,
        )


@bp.route("/contact-emails/<int:id>", methods=["GET"])
def show_contact_email(id: int) -> ResponseReturnValue:
    """問い合わせメール詳細画面"""
    mail = db.session.get(ContactEmail, id)
    if not mail:
        abort(404)
    form = NjkMemoForm(njk_memo=mail.njk_memo)
    return render_template("show_contact_email.html", mail=mail, form=form)


@bp.route("/contact-emails/<int:id>/update", methods=["POST"])
def update_contact_email(id: int) -> ResponseReturnValue:
    """問い合わせメールの更新処理"""
    mail = db.session.get(ContactEmail, id)
    if not mail:
        abort(404)

    form = NjkMemoForm()
    if form.validate_on_submit():
        mail.njk_memo = form.njk_memo.data
        # 入力が空文字や空白のみの場合は False、それ以外は True
        mail.is_njk_memo_present = bool(form.njk_memo.data.strip())
        db.session.commit()
        flash("NJK記入欄を保存しました", "success")
    else:
        flash("入力内容にエラーがあります。再度ご確認ください。", "warning")

    return redirect(url_for("main.show_contact_email", id=id))


@bp.route("/contact_emails/<int:id>", methods=["POST"])
def delete_contact_email(id: int) -> ResponseReturnValue:
    """問い合わせメール削除"""
    mail = db.session.get(ContactEmail, id)
    if not mail:
        abort(404)
    db.session.delete(mail)
    db.session.commit()
    flash("問い合わせメールが削除されました", "success")

    # 検索条件を削除前の状態に設定する
    search_params = request.form.to_dict()
    search_params.pop('csrf_token', None)  # csrf_tokenは不要
    return redirect(url_for("main.list_contact_emails", **search_params))  # type: ignore


@bp.route("/job-emails", methods=["GET", "DELETE"])
def list_job_emails() -> ResponseReturnValue:
    """求人関係メール一覧画面"""
    form = JobEmailSearchForm(request.args)

    # 検索フォームの日付の不正な入力値をクリア
    is_valid, cleaned_params = services.validate_input(form)

    if not is_valid:
        # 不正な値のクエリパラメータをクリアするためのリダイレクト
        return redirect(url_for("main.list_job_emails", **cleaned_params))  # type: ignore

    # フォームの検索結果
    query = JobEmail.query
    query = services.search_job_emails(query=query, form=form)

    # 並べ替え機能
    order = request.args.get("order", "desc")
    query = services.sort_emails_by_received_at(query=query, model=JobEmail, order=order)

    # ページ送り機能
    page = request.args.get(get_page_parameter(), type=int, default=1)
    mails, pagination = services.paginate_query(query=query, page=page, per_page=PER_PAGE)

    delete_button_form = MailDeleteButtonForm()
    access_button_form = AccessButtonForm()

    return render_template(
        "list_job_emails.html",
        mails=mails,
        form=form,
        pagination=pagination,
        delete_button_form=delete_button_form,
        access_button_form=access_button_form,
        )


@bp.route("/job-emails/<int:id>", methods=["GET"])
def show_job_email(id: int) -> ResponseReturnValue:
    """求人関係メール詳細画面"""
    mail = db.session.get(JobEmail, id)
    if not mail:
        abort(404)
    form = NjkMemoForm(njk_memo=mail.njk_memo)
    return render_template("show_job_email.html", mail=mail, form=form)


@bp.route("/job-emails/<int:id>/update", methods=["POST"])
def update_job_email(id: int) -> ResponseReturnValue:
    """求人関係メールの更新処理"""
    mail = db.session.get(JobEmail, id)
    if not mail:
        abort(404)

    form = NjkMemoForm()
    if form.validate_on_submit():
        mail.njk_memo = form.njk_memo.data
        # 入力が空文字や空白のみの場合は False、それ以外は True
        mail.is_njk_memo_present = bool(form.njk_memo.data.strip())
        db.session.commit()
        flash("NJK記入欄を保存しました", "success")
    else:
        flash("入力内容にエラーがあります。再度ご確認ください。", "warning")

    return redirect(url_for("main.show_job_email", id=id))


@bp.route("/job_emails/<int:id>", methods=["POST"])
def delete_job_email(id: int) -> ResponseReturnValue:
    """求人関係メール削除"""
    mail = db.session.get(JobEmail, id)
    if not mail:
        abort(404)
    db.session.delete(mail)
    db.session.commit()
    flash("求人関係メールが削除されました", "success")

    # 検索条件を削除前の状態に設定する
    search_params = request.form.to_dict()
    search_params.pop('csrf_token', None)  # csrf_tokenは不要
    return redirect(url_for("main.list_job_emails", **search_params))  # type: ignore


@bp.route("/contact-emails/<int:id>/access", methods=["POST"])
def access_contact_email(id: int) -> ResponseReturnValue:
    """問い合わせメールアクセス処理"""
    mail = db.session.get(ContactEmail, id)
    if not mail:
        abort(404)
    mail.is_detail_accessed = True
    db.session.commit()

    return redirect(url_for("main.show_contact_email", id=id))


@bp.route("/job-emails/<int:id>/access", methods=["POST"])
def access_job_email(id: int) -> ResponseReturnValue:
    """求人関係メールアクセス処理"""
    mail = db.session.get(JobEmail, id)
    if not mail:
        abort(404)
    mail.is_detail_accessed = True
    db.session.commit()

    return redirect(url_for("main.show_job_email", id=id))


@bp.app_errorhandler(NotFound)
def show_404_page(error: HTTPException) -> ResponseReturnValue:
    """404 NotFoundエラー画面"""
    msg: str | None = error.description
    logger.error("404エラー: %s", msg)
    return render_template("errors/404.html"), 404


@bp.app_errorhandler(InternalServerError)
def show_500_page(error: HTTPException) -> ResponseReturnValue:
    """500 内部サーバーエラー画面"""
    msg: str | None = error.description
    logger.error("500エラー: %s", msg, exc_info=True)
    return render_template("errors/500.html"), 500

app/templates/_helpers.html
<!-- 受信日時のソートリンクを生成するマクロ -->
{% macro toggle_received_at_link(endpoint, page_params) %}
{% set current_order = page_params.pop("order", None) %}
{% set _ = page_params.pop("page", None) %}

{% if current_order == "asc" %}
        <a href="{{ url_for(endpoint, order='desc', page=1, **page_params) }}">受信日時▲</a>
    {% else %}
        <a href="{{ url_for(endpoint, order='asc', page=1, **page_params) }}">受信日時▼</a>
    {% endif %}
{% endmacro %}

<!-- 共通なモーダルダイアログを生成するマクロ -->
{% macro modal_dialog(modal_id, modal_label, icon_class, body_message, confirm_btn_id, confirm_btn_text, cancel_btn_text, confirm_btn_class='btn-danger') %}
<div class="modal fade" id="{{ modal_id }}" tabindex="-1" aria-labelledby="{{ modal_id }}Label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-secondary-subtle">
                <p class="modal-title h5" id="{{ modal_id }}Label">
                    {% if icon_class %}
                        <i class="{{ icon_class }} me-2"></i>
                    {% endif %}
                    {{ modal_label }}
                </p>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body border-bottom-0">
                {{ body_message }}
            </div>
            <div class="modal-footer border-top-0">
                <button type="button" id="{{ confirm_btn_id }}" class="btn {{ confirm_btn_class }}">
                    {{ confirm_btn_text }}
                </button>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                    {{ cancel_btn_text }}
                </button>
            </div>
        </div>
    </div>
</div>
{% endmacro %}

app/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}MailFilter{% endblock %}</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" type='text/css' href="{{url_for('static', filename='css/style.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.8.1/font/bootstrap-icons.min.css" rel="stylesheet">
    {% block style %}{% endblock %}
    <script src="{{url_for('static', filename='js/clear_sessionstorage.js')}}" type="module"></script>
    <script src="{{url_for('static', filename='js/back_to_top.js')}}" type="module"></script>
    {% block script %}{% endblock %}
</head>

<body>
    <!-- ヘッダー部 -->
    <header class="bg-secondary text-white p-3">
        <nav class="navbar navbar-expand-lg navbar-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url_for('main.index') }}">
                    <i class="bi bi-envelope-fill"></i> MailFilter
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.list_contact_emails') }}" >問い合わせメール</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url_for('main.list_job_emails') }}">求人関係メール</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <!-- フラッシュメッセージの表示エリア -->
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="container-fluid">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible fade show mt-2" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>                    
            </div>
            {% endfor %}
        </div>
        {% endif %}
    {% endwith %}

    {% block content %}内容{% endblock %}

    <!-- フッター部 -->
    <footer class="bg-dark text-white text-center p-3 mt-auto">
        <div class="container">
            <p>© NihonJimuKaihatsu Co., Ltd.</p>
        </div>
    </footer>

    <!-- 上へ戻るボタン -->
    <button id="backToTop" class="btn btn-primary position-fixed bottom-0 end-0 m-3" style="display: none;">
        <i class="bi bi-arrow-up"></i>
    </button>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</body>
</html>

app/templates/list_contact_emails.html
{% extends 'base.html' %}

{% from "_helpers.html" import toggle_received_at_link %}

{% block title %}MailFilter-問い合わせメール一覧{% endblock %}

{% block script %}
    <script src="{{url_for('static', filename='js/set_date_placeholder.js')}}" type="module"></script>
    <script src="{{url_for('static', filename='js/set_selectbox_color.js')}}" type="module"></script>
    <script src="{{url_for('static', filename='js/reset_form.js')}}" type="module"></script>
    <script src="{{url_for('static', filename='js/save_contact_emails_search_conditions.js')}}" type="module"></script>
    <script src="{{url_for('static', filename='js/modal.js')}}" type="module"></script>
{% endblock %}

{% block content %}
<div class="container-fluid mt-5">
    <div class="container">
        
        <!-- タイトル -->
        <div class="d-flex align-items-center mb-4">
            <i class="bi bi-robot text-primary fs-3 me-2"></i>
            <h1 class="h3 mb-0">問い合わせメール一覧</h1>
        </div>
  
        <!-- 検索フォーム -->
        <form id="searchForm" class="row g-3 mb-5" method="GET" action="{{ url_for('main.list_contact_emails') }}">
            <p class="h5 fw-light">検索条件を入力してください</p>
            <div class="col-md-9">         
                <div class="mb-3">
                    {{ form.keyword(id="keyword", class="form-control") }}
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        {{ form.start_date(id="start_date", class="form-control") }}
                    </div>
                    <div class="col-md-6">
                        {{ form.end_date(id="end_date", class="form-control") }}
                    </div>
                </div>
                <div class="mb-3">
                    {{ form.type(id="type", class="form-select") }}
                </div>
            </div>
            <div class="col-md-3 d-flex flex-column justify-content-end mb-3">
                {{ form.search(id="execute", class="btn btn-success mb-2 w-100") }}
                <button type="button" id="clear" class="btn btn-warning w-100">クリア</button>
            </div>
        </form>
    </div>

    <!-- メール一覧 -->
    <table class="table table-striped">
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th class="ps-4">{{ toggle_received_at_link("main.list_contact_emails", request.args.to_dict()) }}</th>
                <th>問い合わせ種別</th>
                <th>問い合わせ内容</th>
                <th>送信元メールアドレス</th>
            </tr>
        </thead>
        <tbody>
            {% for mail in mails %}
            <tr class="align-middle">
                <td class="px-1 max-width-40">
                {% if mail.is_detail_accessed %}
                    <a href="{{ url_for('main.show_contact_email', id=mail.id) }}" class="btn btn-outline-primary btn-sm p-1">詳細</a>
                {% else %}
                    <form action="{{ url_for('main.access_contact_email', id=mail.id) }}" method="POST">
                        {{ access_button_form.hidden_tag() }}
                        {{ access_button_form.access_button }}
                    </form>
                {% endif %}
                </td>
                <td class="px-1 max-width-40">
                    <!-- 削除ボタン -->
                    <form id="delete-form-{{ mail.id }}" action="{{ url_for('main.delete_contact_email', id=mail.id) }}" method="POST" style="display: none;">
                        {{ delete_button_form.hidden_tag() }}
                        <input type="hidden" name="_method" value="DELETE">
                        <!-- クエリパラメータをhiddenフォームとして追加 -->
                        {% for key, value in request.args.items() %}
                            <input type="hidden" name="{{ key }}" value="{{ value }}">
                        {% endfor %}
                    </form>
                    <button id="delete-button-{{ mail.id }}" 
                        data-modal-target="#deleteModal" 
                        data-confirm-target="#confirmDeleteBtn" 
                        data-form-id="delete-form-{{ mail.id }}"
                        class="btn btn-outline-danger btn-sm p-1">
                    削除
                    </button>
                </td>
                <td class="px-1">
                    {% if mail.is_detail_accessed %}
                        <i class="bi bi-check2 text-success fs-6"></i>
                    {% else %}
                        <i class="bi bi-check2 text-success text-opacity-25 fs-6"></i>
                    {% endif %}
                </td>
                <td class="px-1">
                    {% if mail.is_njk_memo_present %}
                        <i class="bi bi-journal-text text-success fs-6"></i>
                    {% else %}
                        <i class="bi bi-journal-text text-success text-opacity-25 fs-6"></i>
                    {% endif %}
                </td>
                <td>{{mail.received_at.strftime('%Y/%m/%d %H:%M:%S')}}</td>
                <td>{{mail.contact_type | contact_type}}</td>
                <td>{{mail.content | truncate(28, True, end='...')}}</td>
                <td>{{mail.email | truncate(18, True, end='...')}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="container-fluid mt-5 mb-2">
        <nav aria-label="Page navigation" class="row align-items-center">
            <div class="col-12 col-md-4 text-start mb-3 mb-md-0">{{ pagination.info }}</div>
            <div class="col-12 col-md-4 text-center mb-3 mb-md-0">{{ pagination.links }}</div>
            <div class="col-12 col-md-4 text-end mb-3 mb-md-0">{{ pagination.page }} / {{ pagination.total_pages }} ページ</div>
        </nav>
    </div>
</div>

{% from "_helpers.html" import modal_dialog %}

<!-- メール削除時のモーダルダイアログ -->
{{ modal_dialog(
    modal_id='deleteModal',
    modal_label='確認',
    icon_class='bi bi-exclamation-triangle-fill',
    body_message='メールを削除します。よろしいですか？',
    confirm_btn_id='confirmDeleteBtn',
    confirm_btn_text='はい',
    confirm_btn_class='btn-danger',
    cancel_btn_text='いいえ',
) }}

{% endblock %}

app/templates/list_job_emails.html
{% extends 'base.html' %}

{% from "_helpers.html" import toggle_received_at_link %}

{% block title %}MailFilter-求人関係メール一覧{% endblock %}

{% block script %}
    <script src="{{url_for('static', filename='js/set_date_placeholder.js')}}" type="module"></script>
    <script src="{{url_for('static', filename='js/reset_form.js')}}" type="module"></script>
    <script src="{{url_for('static', filename='js/save_job_emails_search_conditions.js')}}" type="module"></script>
    <script src="{{url_for('static', filename='js/modal.js')}}" type="module"></script>
{% endblock %}

{% block content %}
<div class="container-fluid mt-5">
    <div class="container">

        <!-- タイトル -->
        <div class="d-flex align-items-center mb-4">
            <i class="bi bi-people-fill text-primary fs-3 me-2"></i>
            <h1 class="h3 mb-0">求人関係メール一覧</h1>
        </div>

        <!-- 検索フォーム -->
        <div class="container">
            <form id="searchForm" class="row g-3 mb-5 align-items-end" method="GET" action="{{ url_for('main.list_job_emails') }}">
                <p class="h5 fw-light">検索条件を入力してください</p>
                <div class="col-md-9">
                    <div class="mb-3">
                        {{ form.keyword(id="keyword", class="form-control") }}
                    </div>
                    <div class="row mb-3">
                        <div class="col-md-6">
                            {{ form.start_date(id="start_date", class="form-control") }}
                        </div>
                        <div class="col-md-6">
                            {{ form.end_date(id="end_date", class="form-control") }}
                        </div>
                    </div>
                </div>
                <div class="col-md-3 d-flex flex-column justify-content-end mb-3">
                    {{ form.search(id="execute", class="btn btn-success mb-2 w-100") }}
                    <button type="button" id="clear" class="btn btn-warning w-100">クリア</button>
                </div>
            </form>
        </div>
    </div>

    <!-- メール一覧 -->
    <table class="table table-striped">
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th></th>
                <th></th>
                <th class="ps-4">{{ toggle_received_at_link("main.list_job_emails", request.args.to_dict()) }}</th>
                <th>件名</th>
                <th>送信元メールアドレス</th>
            </tr>
        </thead>
        <tbody>
            {% for mail in mails %}
            <tr class="align-middle">
                <td  class="px-1 max-width-40">
                    {% if mail.is_detail_accessed %}
                        <a href="{{ url_for('main.show_job_email', id=mail.id) }}" class="btn btn-outline-primary btn-sm p-1">詳細</a>
                    {% else %}
                        <form action="{{ url_for('main.access_job_email', id=mail.id) }}" method="POST">
                            {{ access_button_form.hidden_tag() }}
                            {{ access_button_form.access_button }}
                        </form>
                    {% endif %}
                </td>
                <td class="px-1 max-width-40">
                    <!-- 削除ボタン -->
                    <form id="delete-form-{{ mail.id }}" action="{{ url_for('main.delete_job_email', id=mail.id) }}" method="POST" style="display: none;">
                        {{ delete_button_form.hidden_tag() }}
                        <input type="hidden" name="_method" value="DELETE">
                        <!-- クエリパラメータをhiddenフォームとして追加 -->
                        {% for key, value in request.args.items() %}
                            <input type="hidden" name="{{ key }}" value="{{ value }}">
                        {% endfor %}
                    </form>
                    <button id="delete-button-{{ mail.id }}" 
                        data-modal-target="#deleteModal" 
                        data-confirm-target="#confirmDeleteBtn" 
                        data-form-id="delete-form-{{ mail.id }}"
                        class="btn btn-outline-danger btn-sm p-1">
                    削除
                    </button>
                </td>
                <td class="px-1">
                    {% if mail.is_detail_accessed %}
                        <i class="bi bi-check2 text-success fs-6"></i>
                    {% else %}
                        <i class="bi bi-check2 text-success text-opacity-25 fs-6"></i>
                    {% endif %}
                </td>
                <td class="px-1">
                    {% if mail.is_njk_memo_present %}
                        <i class="bi bi-journal-text text-success fs-6"></i>
                    {% else %}
                        <i class="bi bi-journal-text text-success text-opacity-25 fs-6"></i>
                    {% endif %}
                </td>                
                <td class="ps-4">{{mail.received_at.strftime('%Y/%m/%d %H:%M:%S')}}</td>
                <td>{{mail.subject | truncate(34, True, end='...')}}</td>
                <td>{{mail.email | truncate(20, True, end='...')}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="container-fluid mt-5 mb-2">
        <nav aria-label="Page navigation" class="row align-items-center">
            <div class="col-12 col-md-4 text-start mb-3 mb-md-0">{{ pagination.info }}</div>
            <div class="col-12 col-md-4 text-center mb-3 mb-md-0">{{ pagination.links }}</div>
            <div class="col-12 col-md-4 text-end mb-3 mb-md-0">{{ pagination.page }} / {{ pagination.total_pages }} ページ</div>
        </nav>
    </div>
</div>
{% from "_helpers.html" import modal_dialog %}

<!-- メール削除時のモーダルダイアログ -->
{{ modal_dialog(
    modal_id='deleteModal',
    modal_label='確認',
    icon_class='bi bi-exclamation-triangle-fill',
    body_message='メールを削除します。よろしいですか？',
    confirm_btn_id='confirmDeleteBtn',
    confirm_btn_text='はい',
    confirm_btn_class='btn-danger',
    cancel_btn_text='いいえ',
) }}

{% endblock %}

app/templates/show_contact_email.html
{% extends 'base.html' %}

{% block title %}MailFilter-問い合わせメール詳細{% endblock %}

{% block script %}
<script src="{{url_for('static', filename='js/restore_contact_emails_search_conditions.js')}}" type="module"></script>
<script src="{{url_for('static', filename='js/modal.js')}}" type="module"></script>
{% endblock %}

{% block content %}
<div class="container-fluid mt-5">
    <!-- タイトル -->
    <div class="d-flex align-items-center mb-4">
        <i class="bi bi-robot text-primary fs-3 me-2"></i>
        <h1 class="h3 mb-0">問い合わせメール詳細</h1>
    </div>
    <div class="card">
        <div class="card-header">NJK記入欄（自由記入） <span class="text-success">※ 100文字まで入力できます</span></div>
        <div class="card-body">
            <p class="card-text">
                <form id="save-form-{{ mail.id }}" method="POST" action="{{ url_for('main.update_contact_email', id=mail.id) }}">
                    {{ form.hidden_tag() }}
                    {{ form.njk_memo }}
                </form>
                <button id="save-button-{{ mail.id }}" 
                data-modal-target="#saveNJKModal" 
                data-confirm-target="#confirmSaveNJKBtn" 
                data-form-id="save-form-{{ mail.id }}"
                class="btn btn-outline-success mt-2">
                保存
            </button>
            </p>
        </div>
    </div>
    <div class="card mt-3">
        <div class="card-header">詳細情報</div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><dt>ID</dt><dd>{{mail.id}}</dd></li>
            <li class="list-group-item"><dt>問い合わせ種別</dt><dd>{{mail.contact_type | contact_type}}</dd></li>
            <li class="list-group-item"><dt>問い合わせ内容</dt><dd class="preformatted">{{mail.content}}</dd></li>
            <li class="list-group-item"><dt>お名前</dt><dd>{{mail.name}}</dd></li>
            <li class="list-group-item"><dt>よみがな</dt><dd>{{mail.kana}}</dd></li>
            <li class="list-group-item"><dt>メールアドレス</dt><dd>{{mail.email}}</dd></li>
            <li class="list-group-item"><dt>性別</dt><dd>{{mail.gender | gender}}</dd></li>
            <li class="list-group-item"><dt>送信元IPアドレス</dt><dd>{{mail.ip}}</dd></li>
            <li class="list-group-item"><dt>受信日時</dt><dd>{{mail.received_at.strftime('%Y/%m/%d %H:%M:%S')}}</dd></li>
        </ul>
    </div>
    <div class="card-footer my-3">
        <a id="backToList" href="{{ url_for('main.list_contact_emails') }}" class="btn btn-outline-primary">一覧に戻る</a>
    </div>
</div>

{% from "_helpers.html" import modal_dialog %}

<!-- NJK記入欄保存時のモーダルダイアログ -->
{{ modal_dialog(
    modal_id='saveNJKModal',
    modal_label='確認',
    icon_class='bi bi-info-circle',
    body_message='NJK記入欄を保存します。よろしいですか？',
    confirm_btn_id='confirmSaveNJKBtn',
    confirm_btn_text='はい',
    confirm_btn_class='btn-primary',
    cancel_btn_text='いいえ',
) }}

{% endblock %}